### ISSUE TITLE
Update to new Valheim release

### ISSUE THREAD

**Issue by kibiz0r** [aidalgol/valheim-server-flake#10]
Manifest and hash are out of date now.

I just started using Nix 2 days ago, so I was thinking this might be a good use for overlays, but I couldn't even figure out how to get started trying to overlay this.

I realize that by the time you read this, the easiest fix is just to update the manifest and sha. But if you have a moment to teach me a little bit, I would really appreciate understanding how to handle a situation like this from a strictly user's perspective.

Also: Thank you for starting this project! I'm excited to have a non-docker but still reproducible way to host Valheim.

**Comment by aidalgol** [comment]
When you only want to update the version of a package, you use `overrideAttrs` on the package derivation to override the `version` and `src` attributes.  Some types of packages are more complicated, such as Go, Rust, and NPM/Yarn packages, because you also need to override the dependencies hash.  You may also need to make other changes in the override depending on what has changed upstream.

Unfortunately, this Valheim server package is a bad example for learning how to do this, because of the hacks to get it to work, which as a side-effect makes overriding the package a bit trickier.
